version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    working_dir: /app
    tty: true
  front:
    build: ./front
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    working_dir: /app
    tty: true
